// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballAPI.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20250731154147_SeedPlayers")]
    partial class SeedPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballAPI.Models.FootballPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CurrentTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FootballPlayers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 40,
                            CurrentTeam = "Al Nassr",
                            Height = 1.92f,
                            Name = "Cristiano Ronaldo",
                            Position = "Forward"
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            CurrentTeam = "Manchester City",
                            Height = 1.94f,
                            Name = "Erling Haaland",
                            Position = "Striker"
                        },
                        new
                        {
                            Id = 3,
                            Age = 33,
                            CurrentTeam = "Manchester City",
                            Height = 1.81f,
                            Name = "Kevin De Bruyne",
                            Position = "Midfielder"
                        },
                        new
                        {
                            Id = 4,
                            Age = 32,
                            CurrentTeam = "Liverpool",
                            Height = 1.93f,
                            Name = "Virgil van Dijk",
                            Position = "Defender"
                        },
                        new
                        {
                            Id = 5,
                            Age = 33,
                            CurrentTeam = "Real Madrid",
                            Height = 2f,
                            Name = "Thibaut Courtois",
                            Position = "Goalkeeper"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
